; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -aarch64-sve-vector-bits-min=256  < %s | FileCheck %s -check-prefixes=CHECK,VBITS_GE_256
; RUN: llc -aarch64-sve-vector-bits-min=512  < %s | FileCheck %s -check-prefixes=CHECK,VBITS_GE_512
; RUN: llc -aarch64-sve-vector-bits-min=2048 < %s | FileCheck %s -check-prefixes=CHECK,VBITS_GE_512

target triple = "aarch64-unknown-linux-gnu"

define <4 x bfloat> @select_v4bf16(<4 x bfloat> %op1, <4 x bfloat> %op2, <4 x i1> %mask) vscale_range(2,0) #0 {
; CHECK-LABEL: select_v4bf16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    shl v2.4h, v2.4h, #15
; CHECK-NEXT:    cmlt v2.4h, v2.4h, #0
; CHECK-NEXT:    bif v0.8b, v1.8b, v2.8b
; CHECK-NEXT:    ret
  %sel = select <4 x i1> %mask, <4 x bfloat> %op1, <4 x bfloat> %op2
  ret <4 x bfloat> %sel
}

define <8 x bfloat> @select_v8bf16(<8 x bfloat> %op1, <8 x bfloat> %op2, <8 x i1> %mask) vscale_range(2,0) #0 {
; CHECK-LABEL: select_v8bf16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ushll v2.8h, v2.8b, #0
; CHECK-NEXT:    shl v2.8h, v2.8h, #15
; CHECK-NEXT:    cmlt v2.8h, v2.8h, #0
; CHECK-NEXT:    bif v0.16b, v1.16b, v2.16b
; CHECK-NEXT:    ret
  %sel = select <8 x i1> %mask, <8 x bfloat> %op1, <8 x bfloat> %op2
  ret <8 x bfloat> %sel
}

define void @select_v16bf16(ptr %a, ptr %b, ptr %c) vscale_range(2,0) #0 {
; CHECK-LABEL: select_v16bf16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.h, vl16
; CHECK-NEXT:    mov x8, #8 // =0x8
; CHECK-NEXT:    ld1h { z0.h }, p0/z, [x2]
; CHECK-NEXT:    cmpeq p1.h, p0/z, z0.h, #0
; CHECK-NEXT:    ptrue p0.h, vl8
; CHECK-NEXT:    mov z0.h, p1/z, #-1 // =0xffffffffffffffff
; CHECK-NEXT:    movprfx z1, z0
; CHECK-NEXT:    ext z1.b, z1.b, z0.b, #16
; CHECK-NEXT:    cmpeq p2.h, p0/z, z0.h, #0
; CHECK-NEXT:    cmpeq p1.h, p0/z, z1.h, #0
; CHECK-NEXT:    ldp q1, q0, [x1]
; CHECK-NEXT:    st1h { z1.h }, p2, [x0]
; CHECK-NEXT:    st1h { z0.h }, p1, [x0, x8, lsl #1]
; CHECK-NEXT:    ret
  %op1 = load <16 x bfloat>, ptr %a
  %op2 = load <16 x bfloat>, ptr %b
  %mask.ext = load <16 x i16>, ptr %c
  %mask = icmp eq <16 x i16> %mask.ext, zeroinitializer
  %sel = select <16 x i1> %mask, <16 x bfloat> %op1, <16 x bfloat> %op2
  store <16 x bfloat> %sel, ptr %a
  ret void
}

define void @select_v32bf16(ptr %a, ptr %b, ptr %c) #0 {
;
; VBITS_GE_256-LABEL: select_v32bf16:
; VBITS_GE_256:       // %bb.0:
; VBITS_GE_256-NEXT:    ptrue p0.h, vl16
; VBITS_GE_256-NEXT:    mov x8, #16 // =0x10
; VBITS_GE_256-NEXT:    mov x9, #24 // =0x18
; VBITS_GE_256-NEXT:    ld1h { z0.h }, p0/z, [x2, x8, lsl #1]
; VBITS_GE_256-NEXT:    ld1h { z1.h }, p0/z, [x2]
; VBITS_GE_256-NEXT:    ptrue p0.h, vl8
; VBITS_GE_256-NEXT:    movprfx z2, z0
; VBITS_GE_256-NEXT:    ext z2.b, z2.b, z0.b, #16
; VBITS_GE_256-NEXT:    movprfx z3, z1
; VBITS_GE_256-NEXT:    ext z3.b, z3.b, z1.b, #16
; VBITS_GE_256-NEXT:    cmpne p1.h, p0/z, z0.h, #0
; VBITS_GE_256-NEXT:    cmpne p4.h, p0/z, z1.h, #0
; VBITS_GE_256-NEXT:    cmpne p2.h, p0/z, z2.h, #0
; VBITS_GE_256-NEXT:    cmpne p3.h, p0/z, z3.h, #0
; VBITS_GE_256-NEXT:    ldp q0, q2, [x1, #32]
; VBITS_GE_256-NEXT:    ldp q1, q3, [x1]
; VBITS_GE_256-NEXT:    st1h { z0.h }, p1, [x0, x8, lsl #1]
; VBITS_GE_256-NEXT:    mov x8, #8 // =0x8
; VBITS_GE_256-NEXT:    st1h { z2.h }, p2, [x0, x9, lsl #1]
; VBITS_GE_256-NEXT:    st1h { z3.h }, p3, [x0, x8, lsl #1]
; VBITS_GE_256-NEXT:    st1h { z1.h }, p4, [x0]
; VBITS_GE_256-NEXT:    ret
;
; VBITS_GE_512-LABEL: select_v32bf16:
; VBITS_GE_512:       // %bb.0:
; VBITS_GE_512-NEXT:    ptrue p0.h, vl32
; VBITS_GE_512-NEXT:    mov x8, #16 // =0x10
; VBITS_GE_512-NEXT:    ld1h { z0.h }, p0/z, [x2]
; VBITS_GE_512-NEXT:    cmpeq p1.h, p0/z, z0.h, #0
; VBITS_GE_512-NEXT:    ptrue p0.h, vl8
; VBITS_GE_512-NEXT:    mov z0.h, p1/z, #-1 // =0xffffffffffffffff
; VBITS_GE_512-NEXT:    movprfx z1, z0
; VBITS_GE_512-NEXT:    ext z1.b, z1.b, z0.b, #32
; VBITS_GE_512-NEXT:    movprfx z2, z0
; VBITS_GE_512-NEXT:    ext z2.b, z2.b, z0.b, #16
; VBITS_GE_512-NEXT:    cmpeq p4.h, p0/z, z0.h, #0
; VBITS_GE_512-NEXT:    ldr q0, [x1, #48]
; VBITS_GE_512-NEXT:    movprfx z3, z1
; VBITS_GE_512-NEXT:    ext z3.b, z3.b, z1.b, #16
; VBITS_GE_512-NEXT:    cmpeq p1.h, p0/z, z1.h, #0
; VBITS_GE_512-NEXT:    cmpeq p2.h, p0/z, z2.h, #0
; VBITS_GE_512-NEXT:    ldr q2, [x1]
; VBITS_GE_512-NEXT:    cmpeq p3.h, p0/z, z3.h, #0
; VBITS_GE_512-NEXT:    ldp q3, q1, [x1, #16]
; VBITS_GE_512-NEXT:    st1h { z2.h }, p4, [x0]
; VBITS_GE_512-NEXT:    st1h { z1.h }, p1, [x0, x8, lsl #1]
; VBITS_GE_512-NEXT:    mov x8, #8 // =0x8
; VBITS_GE_512-NEXT:    st1h { z3.h }, p2, [x0, x8, lsl #1]
; VBITS_GE_512-NEXT:    mov x8, #24 // =0x18
; VBITS_GE_512-NEXT:    st1h { z0.h }, p3, [x0, x8, lsl #1]
; VBITS_GE_512-NEXT:    ret
  %op1 = load <32 x bfloat>, ptr %a
  %op2 = load <32 x bfloat>, ptr %b
  %mask.ext = load <32 x i16>, ptr %c
  %mask = icmp eq <32 x i16> %mask.ext, zeroinitializer
  %sel = select <32 x i1> %mask, <32 x bfloat> %op1, <32 x bfloat> %op2
  store <32 x bfloat> %sel, ptr %a
  ret void
}

define void @select_v64bf16(ptr %a, ptr %b, ptr %c) vscale_range(8,0) #0 {
; CHECK-LABEL: select_v64bf16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.h, vl64
; CHECK-NEXT:    ldp q18, q17, [x1, #64]
; CHECK-NEXT:    ldp q7, q6, [x1, #32]
; CHECK-NEXT:    mov x9, #32 // =0x20
; CHECK-NEXT:    ld1h { z0.h }, p0/z, [x2]
; CHECK-NEXT:    ldp q4, q3, [x1, #96]
; CHECK-NEXT:    mov x8, #16 // =0x10
; CHECK-NEXT:    cmpeq p1.h, p0/z, z0.h, #0
; CHECK-NEXT:    ptrue p0.h, vl8
; CHECK-NEXT:    mov z0.h, p1/z, #-1 // =0xffffffffffffffff
; CHECK-NEXT:    movprfx z1, z0
; CHECK-NEXT:    ext z1.b, z1.b, z0.b, #64
; CHECK-NEXT:    movprfx z2, z0
; CHECK-NEXT:    ext z2.b, z2.b, z0.b, #32
; CHECK-NEXT:    movprfx z5, z0
; CHECK-NEXT:    ext z5.b, z5.b, z0.b, #16
; CHECK-NEXT:    movprfx z16, z1
; CHECK-NEXT:    ext z16.b, z16.b, z1.b, #32
; CHECK-NEXT:    cmpeq p1.h, p0/z, z1.h, #0
; CHECK-NEXT:    ext z1.b, z1.b, z1.b, #16
; CHECK-NEXT:    cmpeq p2.h, p0/z, z2.h, #0
; CHECK-NEXT:    ext z2.b, z2.b, z2.b, #16
; CHECK-NEXT:    cmpeq p3.h, p0/z, z5.h, #0
; CHECK-NEXT:    cmpeq p4.h, p0/z, z16.h, #0
; CHECK-NEXT:    movprfx z5, z16
; CHECK-NEXT:    ext z5.b, z5.b, z16.b, #16
; CHECK-NEXT:    ldp q16, q19, [x1]
; CHECK-NEXT:    st1h { z18.h }, p1, [x0, x9, lsl #1]
; CHECK-NEXT:    cmpeq p1.h, p0/z, z1.h, #0
; CHECK-NEXT:    mov x9, #8 // =0x8
; CHECK-NEXT:    st1h { z7.h }, p2, [x0, x8, lsl #1]
; CHECK-NEXT:    cmpeq p2.h, p0/z, z2.h, #0
; CHECK-NEXT:    mov x8, #48 // =0x30
; CHECK-NEXT:    st1h { z19.h }, p3, [x0, x9, lsl #1]
; CHECK-NEXT:    cmpeq p3.h, p0/z, z5.h, #0
; CHECK-NEXT:    st1h { z4.h }, p4, [x0, x8, lsl #1]
; CHECK-NEXT:    cmpeq p4.h, p0/z, z0.h, #0
; CHECK-NEXT:    mov x8, #40 // =0x28
; CHECK-NEXT:    st1h { z17.h }, p1, [x0, x8, lsl #1]
; CHECK-NEXT:    mov x8, #24 // =0x18
; CHECK-NEXT:    st1h { z6.h }, p2, [x0, x8, lsl #1]
; CHECK-NEXT:    mov x8, #56 // =0x38
; CHECK-NEXT:    st1h { z3.h }, p3, [x0, x8, lsl #1]
; CHECK-NEXT:    st1h { z16.h }, p4, [x0]
; CHECK-NEXT:    ret
  %op1 = load <64 x bfloat>, ptr %a
  %op2 = load <64 x bfloat>, ptr %b
  %mask.ext = load <64 x i16>, ptr %c
  %mask = icmp eq <64 x i16> %mask.ext, zeroinitializer
  %sel = select <64 x i1> %mask, <64 x bfloat> %op1, <64 x bfloat> %op2
  store <64 x bfloat> %sel, ptr %a
  ret void
}

define void @select_v128bf16(ptr %a, ptr %b, ptr %c) vscale_range(16,0) #0 {
; CHECK-LABEL: select_v128bf16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.h, vl128
; CHECK-NEXT:    ldp q26, q25, [x1, #128]
; CHECK-NEXT:    ldp q30, q29, [x1, #64]
; CHECK-NEXT:    mov x16, #64 // =0x40
; CHECK-NEXT:    ld1h { z0.h }, p0/z, [x2]
; CHECK-NEXT:    ldp q3, q19, [x1]
; CHECK-NEXT:    ldp q22, q21, [x1, #32]
; CHECK-NEXT:    mov x15, #32 // =0x20
; CHECK-NEXT:    ldp q7, q1, [x1, #96]
; CHECK-NEXT:    mov x13, #8 // =0x8
; CHECK-NEXT:    cmpeq p1.h, p0/z, z0.h, #0
; CHECK-NEXT:    ptrue p0.h, vl8
; CHECK-NEXT:    mov x14, #16 // =0x10
; CHECK-NEXT:    ldp q5, q0, [x1, #224]
; CHECK-NEXT:    mov x12, #96 // =0x60
; CHECK-NEXT:    ldp q16, q4, [x1, #160]
; CHECK-NEXT:    mov x11, #80 // =0x50
; CHECK-NEXT:    ldp q17, q6, [x1, #192]
; CHECK-NEXT:    mov x9, #48 // =0x30
; CHECK-NEXT:    mov z2.h, p1/z, #-1 // =0xffffffffffffffff
; CHECK-NEXT:    mov x10, #72 // =0x48
; CHECK-NEXT:    mov x8, #40 // =0x28
; CHECK-NEXT:    movprfx z18, z2
; CHECK-NEXT:    ext z18.b, z18.b, z2.b, #128
; CHECK-NEXT:    movprfx z20, z2
; CHECK-NEXT:    ext z20.b, z20.b, z2.b, #64
; CHECK-NEXT:    movprfx z23, z2
; CHECK-NEXT:    ext z23.b, z23.b, z2.b, #32
; CHECK-NEXT:    movprfx z24, z2
; CHECK-NEXT:    ext z24.b, z24.b, z2.b, #16
; CHECK-NEXT:    cmpeq p1.h, p0/z, z18.h, #0
; CHECK-NEXT:    movprfx z27, z18
; CHECK-NEXT:    ext z27.b, z27.b, z18.b, #64
; CHECK-NEXT:    cmpeq p2.h, p0/z, z20.h, #0
; CHECK-NEXT:    movprfx z28, z18
; CHECK-NEXT:    ext z28.b, z28.b, z18.b, #32
; CHECK-NEXT:    cmpeq p3.h, p0/z, z23.h, #0
; CHECK-NEXT:    cmpeq p4.h, p0/z, z24.h, #0
; CHECK-NEXT:    ext z18.b, z18.b, z18.b, #16
; CHECK-NEXT:    movprfx z24, z20
; CHECK-NEXT:    ext z24.b, z24.b, z20.b, #32
; CHECK-NEXT:    ext z20.b, z20.b, z20.b, #16
; CHECK-NEXT:    ext z23.b, z23.b, z23.b, #16
; CHECK-NEXT:    st1h { z26.h }, p1, [x0, x16, lsl #1]
; CHECK-NEXT:    cmpeq p1.h, p0/z, z27.h, #0
; CHECK-NEXT:    st1h { z30.h }, p2, [x0, x15, lsl #1]
; CHECK-NEXT:    cmpeq p2.h, p0/z, z28.h, #0
; CHECK-NEXT:    st1h { z22.h }, p3, [x0, x14, lsl #1]
; CHECK-NEXT:    cmpeq p3.h, p0/z, z18.h, #0
; CHECK-NEXT:    movprfx z18, z27
; CHECK-NEXT:    ext z18.b, z18.b, z27.b, #32
; CHECK-NEXT:    st1h { z19.h }, p4, [x0, x13, lsl #1]
; CHECK-NEXT:    cmpeq p4.h, p0/z, z24.h, #0
; CHECK-NEXT:    movprfx z19, z27
; CHECK-NEXT:    ext z19.b, z19.b, z27.b, #16
; CHECK-NEXT:    st1h { z17.h }, p1, [x0, x12, lsl #1]
; CHECK-NEXT:    cmpeq p1.h, p0/z, z20.h, #0
; CHECK-NEXT:    movprfx z17, z28
; CHECK-NEXT:    ext z17.b, z17.b, z28.b, #16
; CHECK-NEXT:    st1h { z16.h }, p2, [x0, x11, lsl #1]
; CHECK-NEXT:    cmpeq p2.h, p0/z, z23.h, #0
; CHECK-NEXT:    movprfx z16, z24
; CHECK-NEXT:    ext z16.b, z16.b, z24.b, #16
; CHECK-NEXT:    st1h { z25.h }, p3, [x0, x10, lsl #1]
; CHECK-NEXT:    cmpeq p3.h, p0/z, z18.h, #0
; CHECK-NEXT:    ext z18.b, z18.b, z18.b, #16
; CHECK-NEXT:    st1h { z7.h }, p4, [x0, x9, lsl #1]
; CHECK-NEXT:    cmpeq p4.h, p0/z, z19.h, #0
; CHECK-NEXT:    mov x9, #24 // =0x18
; CHECK-NEXT:    st1h { z29.h }, p1, [x0, x8, lsl #1]
; CHECK-NEXT:    cmpeq p1.h, p0/z, z17.h, #0
; CHECK-NEXT:    mov x8, #112 // =0x70
; CHECK-NEXT:    st1h { z21.h }, p2, [x0, x9, lsl #1]
; CHECK-NEXT:    cmpeq p2.h, p0/z, z16.h, #0
; CHECK-NEXT:    mov x9, #104 // =0x68
; CHECK-NEXT:    st1h { z5.h }, p3, [x0, x8, lsl #1]
; CHECK-NEXT:    cmpeq p3.h, p0/z, z18.h, #0
; CHECK-NEXT:    mov x8, #88 // =0x58
; CHECK-NEXT:    st1h { z6.h }, p4, [x0, x9, lsl #1]
; CHECK-NEXT:    cmpeq p4.h, p0/z, z2.h, #0
; CHECK-NEXT:    st1h { z4.h }, p1, [x0, x8, lsl #1]
; CHECK-NEXT:    mov x8, #56 // =0x38
; CHECK-NEXT:    st1h { z1.h }, p2, [x0, x8, lsl #1]
; CHECK-NEXT:    mov x8, #120 // =0x78
; CHECK-NEXT:    st1h { z0.h }, p3, [x0, x8, lsl #1]
; CHECK-NEXT:    st1h { z3.h }, p4, [x0]
; CHECK-NEXT:    ret
  %op1 = load <128 x bfloat>, ptr %a
  %op2 = load <128 x bfloat>, ptr %b
  %mask.ext = load <128 x i16>, ptr %c
  %mask = icmp eq <128 x i16> %mask.ext, zeroinitializer
  %sel = select <128 x i1> %mask, <128 x bfloat> %op1, <128 x bfloat> %op2
  store <128 x bfloat> %sel, ptr %a
  ret void
}

attributes #0 = { "target-features"="+sve" }
